[Require ntnu-otter-01.ini]

[Control.Search.Greedy]
Enabled                                 = Always
Entity Label                            = GreedySearch
Debug Level                             = Spew
DB Path                                 = /home/nikolai/lststools/dune/misc/re4utmfinal.sqlite
Result DB Path                          = /home/nikolai/lststools/dune/misc/results.sqlite
Grid Type                               = 2
Grid Size                               = 75

[Monitors.CoveredArea]
Enabled                                 = Always
Entity Label                            = CoveredArea
Debug Level                             = Spew
Grid DB Path                            = /home/nikolai/lststools/dune/misc/coverage.sqlite
Grid Type                               = 1
Grid Size                               = 50
#Planning Bounds                         = 553574.0,7022280.1,555088.8,7023506.6
#Planning Bounds                         = 553582.7,7021973.6,560618.8,7026731.5
Planning Bounds                         = 554060.4,7021026.5,560656.6,7025915.0
Other Vehicles                          = ntnu-otter-03
Timestep Grid Constant Decrease         = 0.0
Timestep Grid Factor Decrease           = 1.0



[Transports.TCP.Server/R1]
Enabled                                 = Simulation
Entity Label                            = TCP for R1
Announce Service                        = true
Port                                    = 9801
#Transports                              = EstimatedState