#[Require ntnu-otter-01.ini]

[SourceEstimators.SingleReceiverEKF]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = EstimatorEKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Max Correction Attempts                 = 1
Filter Timestep                         = 0.50
Receiver Depth                          = -3.0
Qm                                      = 0.1, 0.0, 0.0,
                                          0.0, 0.1, 0.0,
                                          0.0, 0.0, 0.001
Rm                                       = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                        = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.32983, 10.07732


[Simulators.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Hydrophone
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
Delay Between Tag Messages              = 500

