[Require ntnu-otter-01.ini]

[Control.Search.FishSearch]
Enabled                                 = Always
Entity Label                            = FishSearch
Debug Level                             = Spew
ENC DB Path                             = /home/nikolai/lststools/dune/misc/re4utmfinal.sqlite
Working DB Path                         = /home/nikolai/lststools/dune/misc/results.sqlite
Grid Type                               = 1
Grid Size                               = 50
Tag Max Transmission Interval           = 90

#[Simulators.StreamVelocity]
#Default Speed North                     = 0.0
#Default Speed East                      = 0.0

#[Maneuver.FollowReference.AUV]
#Enabled                                 = Never
#
#[Maneuver.FollowReference.ASV]
#Enabled                                 = Never
#Entity Label                            = Follow Reference Maneuver
#Horizontal Tolerance                    = 60.0
#Loitering Radius                        = 60
#Default Speed                           = 50
#Default Speed Units                     = percent
#Use anti-obstacle                       = true
#OMPL Max Time                           = 2.0

# GPS simulator.
[Simulators.GPS]
#Initial Position                        = 63.32832455,10.09648011
#Initial Position                        = 61.907693,5.321088
Initial Position                        = 61.892809,6.704574 # Stryn