#[Require basic.ini]

[Sensors.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Hydrophone
Execution Priority                      = 2
Write full timestamp divider            = 200
Serial Port - Device                    = /dev/ttyUSB0
Serial Port - Baud Rate                 = 115200
Use PPS                                 = true
Initialization String 0 - Command       = LI=01
Initialization String 0 - Reply         = LI=01\r
Initialization String 1 - Command       = FC=67
Initialization String 1 - Reply         = FC=67\r
Initialization String 2 - Command       = LM=08
Initialization String 2 - Reply         = LM=08\r