[Require ntnu-otter-01.ini]

[Maneuver.FollowSystemOtter/sim]
Enabled                                 = Never
[Maneuver.FollowReference.ASV/sim]
Enabled                                 = Never
[Control.Formation.FishTracker/sim]
Enabled                                 = Never

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/sampleInput.txt
Delay Between Tag Messages              = 7000

[Simulators.GPS]
#Initial Position                        = 63.3327124836083,10.0742557717784
Initial Position                        = 63.33115233,10.08207277 0.0

[Simulators.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Hydrophone
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220510nordfjord/analyse/alltags.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20230428/20230428_formationstart.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20230428/20230428_all.csv
Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20230508stryn/analyse/follow64/allDetections.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20230508stryn/analyse/track96-1/allDetections.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
Delay Between Tag Messages              = 500
Use Real Time Delay                     = true
Real Time Delay Multiplyer              = 0.01

[SourceEstimators.FishTag]
Enabled                                 = Always
Debug Level                             = None#Spew
Entity Label                            = FishTagEstimator
Filter Timestep                         = 0.01
x0                                      = 0,0,0
ToA Cov                                 = 0.01
Depth Cov                               = 0.001
SS - Extra Parameters - Name            = receiver_depth,max_jitter,max_updates_per_new_measurement,max_correction_attempts,interval_mode,tag_period
SS - Extra Parameters - Value           = -0.5,0.01,1,0,2,7
#P0                                      = 1, 0, 0,
#                                          0, 1, 0,
#                                          0, 0, 1
Multi Receiver Estimators               = XKFVEL
Single Receiver Estimators              = None
Log Folder and Prefix                   = /home/nikolai/log/predict-
Initial Speed Of Sound                  = 1500

[Simulators.FishTag/R1]
Enabled                                 = Never
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR1
Debug Level                             = Spew
#Initial Tag Position                        = 63.334, 10.083333
Initial Tag Position                        = 63.33050479, 10.07735309
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.00
Time Offset S                           = 0
Receiver Serial                         = 47
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R2]
Enabled                                 = Never
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 0.2
Entity Label                            = FishTagR2
Debug Level                             = Spew
#Initial Receiver Position               = 63.33240, 10.07408
Initial Tag Position                    = 63.33236354, 10.08578595
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 48
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R3]
Enabled                                 = Never
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR3
Debug Level                             = Spew
Initial Tag Position                    = 63.32858, 10.08092
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 0
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 49
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R4]
Enabled                                 = Never
Transmitter ID                          = 200
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR4
Debug Level                             = Spew
Initial Tag Position                        = 63.33046311, 10.08873001
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 50
Send RemoteSensorInfo                   = true
