[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/sampleInput.txt
Delay Between Tag Messages              = 7000

[SourceEstimators.MultipleReceivers]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Estimator
Execution Frequency                     = 1
Reference Coordinate					= 63.334, 10.083333
#Initial position of the fish NED wrt Reference Coordinate
Initial Position                        = 100, 100, 7


[SourceEstimators.FishTagEKFTDoA]
Entity Label                            = TDoA_FishPosition
Enabled                                 = Never
Debug Level 							= None
Execution Frequency                     = 1

#Name of the receiver vehicles
Receiver 1 Carrier Name					= ntnu-otter-01
Receiver 2 Carrier Name					= ntnu-otter-02
Receiver 3 Carrier Name					= ntnu-otter-03

Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
num_states                              = 3
num_inputs                              = 0
num_outputs                             = 4
FishPos Cov                             = 0.1
ToA Cov                                 = 0.1
Depth Cov                               = 0.2
Reference Coordinate				    = 63.334, 10.083333
Initial Position                        = 1000, 1000, 70

[Simulators.FishTag/R1]
Enabled                                 = Always
Execution Frequency                     = 0.142857143
Entity Label                            = FishTagR1
Initial Position                        = 63.334, 10.083333
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset                             = 0
Receiver Serial                         = 47

[Simulators.FishTag/R2]
Enabled                                 = Always
Execution Frequency                     = 0.142857143
Entity Label                            = FishTagR2
Initial Position                        = 63.33240, 10.07408
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset                             = 0
Receiver Serial                         = 48

[Simulators.FishTag/R3]
Enabled                                 = Always
Execution Frequency                     = 0.142857143
Entity Label                            = FishTagR3
Initial Position                        = 63.32858, 10.08092
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset                             = 0
Receiver Serial                         = 49
