[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/sampleInput.txt
Delay Between Tag Messages              = 7000

# For some reason this does not work
[SourceEstimators.MultipleReceivers]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Estimator
Execution Frequency                     = 1
Reference Coordinate					= 63.33, 10.083333
#Initial position of the fish NED wrt Reference Coordinate
Initial Position                        = 0, 0, 0

# Works
[SourceEstimators.FishTagXKF]
Entity Label                            = XKF_FishPosition
Enabled                                 = Never
Debug Level 							= None
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 63.334, 10.083333
Initial Position						= 1000, 1000, 70
Receiver Serial Numbers                 = 47, 48, 49

# status unknown
[SourceEstimators.SingleReceiverEKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = Estimator632
Ranging - SNR Fit                       = -0.0845, 50.8098
#Ranging - SNR Fit                       = -0.0971, 41.6358
Tag ID                                  = 40
Receiver Serial Number                  = 47
Max Correction Attempts                 = 1
Filter Timestep                         = 7
Qm                                      = 0.1, 0.0, 0.0,
                                          0.0, 0.1, 0.0,
                                          0.0, 0.0, 0.001
Rm                                       = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                        = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.334, 10.084333

[SourceEstimators.MultipleReceiverXKF]
Entity Label                            = XKFDEMO
Enabled                                 = Never
Debug Level 							= Spew
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2
Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500
Reference Coordinate					= 63.334, 10.084333
Initial Position						= 1000, 1000, 70
Receiver Serial Numbers                 = 47, 48, 49, 50


[SourceEstimators.MultiReceiverEKF]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = MultiEKF40
#Tag ID                                  = 40
Reference Coordinate					= 63.334, 10.084333

[Simulators.FishTag/R1]
Enabled                                 = Always
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR1
#Initial Position                        = 63.334, 10.083333
Initial Position                        = 63.33050479, 10.07735309
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 47
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R2]
Enabled                                 = Always
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR2
Initial Position                        = 63.33240, 10.07408
Initial Position                        = 63.33236354, 10.08578595
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 48
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R3]
Enabled                                 = Always
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR3
Initial Position                        = 63.32858, 10.08092
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 49
Send RemoteSensorInfo                   = true

[Simulators.FishTag/R4]
Enabled                                 = Never
#Execution Frequency                     = 0.142857143
Execution Frequency                     = 1
Entity Label                            = FishTagR4
Initial Position                        = 63.33046311, 10.08873001
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 50
Send RemoteSensorInfo                   = true
