############################################################################
# Copyright 2013-2019 Norwegian University of Science and Technology (NTNU)#
# Department of Engineering Cybernetics (ITK)                              #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Nikolai Lauvås                                                   #
############################################################################
# Otter USV 01 configuration file.                                         #
############################################################################

[Require basic.ini]

############################################################################
# General Parameters.                                                      #
############################################################################

[General]
Vehicle                                 = ntnu-otter-01

# GPS simulator.
[Simulators.GPS]
#Initial Position                        = 63.32832455,10.09648011
Initial Position                        = 63.3436767,10.2014629 # Gaulosen
#Initial Position                        = 63.342996,10.181862 # Gaulosen collision
#Initial Position                        = 63.3412079,10.1948707

[Control.Formation.FishTracker]
Enabled                                 = Always
Entity Label                            = FishTrackFormationControl
Debug Level 							= Spew
Use anti-collision strategies           = true
Formation Allocator                     = 0
ENC DB Path                             = /home/nikolai/Downloads/NO3-NO4_VL_MR_TR_21022023/ENC_ROOT/targetDir25buf/re4utmfinal.sqlite
Use Incomplete Mover                    = 700.0


[SourceEstimators.FishTag/sim]
Enabled                                 = Simulation
Debug Level                             = None
Entity Label                            = FishTagEstimator
Use Speed Of Sound Measurement          = true
Speed Of Sound - Entity                 = SoundSpeedCalculator
Filter Timestep                         = 0.5
x0                                      = 0,0,0
ToA Cov                                 = 1.0
Depth Cov                               = 0.1
Multi Receiver Estimators               = XKF
Single Receiver Estimators              = None#EKF,UKF,SRUKF
Timestamp Timeout [s]                   = 270

[Supervisors.Trackingtarget]
Enabled                                 = Always
Entity Label                            = FishTrackFormationActivator
Debug Level 							= None
Formation Timeout                       = 30
Timeout Formation Keep                  = true
Taglist Path                            = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220510nordfjord/taglist.db

[Simulators.RemoteSensorSender]
Enabled                                 = Never
Entity Label                            = FishTag
Debug Level 							= Debug
Sync Period                             = 10

[Transports.TCP.Server/R1]
Enabled                                 = Always
Entity Label                            = TCP for R1
Announce Service                        = true
Port                                    = 9801
Transports                              = PlanControl,
                                          Reference
[Transports.TCP.Server/R2]
Enabled                                 = Always
Entity Label                            = TCP for R2
Announce Service                        = true
Port                                    = 9802
Transports                              = PlanControl,
                                          Reference

[Transports.TCP.Server/R3]
Enabled                                 = Simulation, osim
Entity Label                            = TCP for R3
Announce Service                        = true
Port                                    = 9803
Transports                              = RemoteSensorInfo

[Simulators.FishTag/R1]
Enabled                                 = Always
Transmitter ID                          = 200
Execution Frequency                     = 0.071428572#0.142857143
#Execution Frequency                     = 0.03125 #32s
#Execution Frequency                     = 0.02 #50sec
Entity Label                            = FishTagR1
Debug Level                             = None
Initial Tag Position                    = 63.32858, 10.08092
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 0
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 47
Send RemoteSensorInfo                   = true
GPS Source Address Receiver             = ntnu-otter-01
GPS Source Address Transmitter          = caravela
Minimum SNR                             = 15
SNR linear a                            = -0.10
SNR linear b                            = 50

[Simulators.FishTag/R2]
Enabled                                 = Always
Transmitter ID                          = 200
Execution Frequency                     = 0.142857143
#Execution Frequency                     = 0.03125 #32s
#Execution Frequency                     = 0.02 #50sec
Entity Label                            = FishTagR2
Debug Level                             = None
Initial Tag Position                    = 63.32858, 10.08092
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 0
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 49
Send RemoteSensorInfo                   = true
GPS Source Address Receiver             = ntnu-otter-02
GPS Source Address Transmitter          = caravela
Minimum SNR                             = 15
SNR linear a                            = -0.10
SNR linear b                            = 50


[Simulators.FishTag/R3]
Enabled                                 = Always
Transmitter ID                          = 200
Execution Frequency                     = 0.142857143
#Execution Frequency                     = 0.03125 #32s
#Execution Frequency                     = 0.02 #50sec
Entity Label                            = FishTagR3
Debug Level                             = None
Initial Tag Position                    = 63.32858, 10.08092
Initial Receiver Depth                  = 0
Initial Tag Depth                       = 2
Time Disturbance Mean value             = 0
Time Disturbance Standard deviation     = 0.01
Time Offset S                           = 0
Receiver Serial                         = 48
Send RemoteSensorInfo                   = true
GPS Source Address Receiver             = ntnu-otter-03
GPS Source Address Transmitter          = caravela
Minimum SNR                             = 15
SNR linear a                            = -0.10
SNR linear b                            = 50