
[Require basic.ini]

############################################################################
# General Parameters.                                                      #
############################################################################
[IMC Addresses]
ntnu-otter-01                           = 0x2810
ntnu-otter-02                           = 0x2811
ntnu-otter-03                           = 0x2812
ntnu-otter-04                           = 0x2813

[General]
Vehicle                                 = ntnu-otter-01
Vehicle Type                            = asv
Speed Conversion -- Actuation           = 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0
Speed Conversion -- RPM                 = 0.0, 120, 245, 360, 490, 615, 725, 845, 980, 980, 980
Speed Conversion -- MPS                 = 0.0, 1.0, 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.09, 3.09, 3.09
Absolute Maximum Depth                  = 0
Time Of Arrival Factor                  = 5.0

[MotionPlanners.newOMPL]
Enabled = Always
Entity Label = newOMPL
Debug Level = Spew
DB Path                                 = /home/nikolai/lststools/dune/misc/combined.sqlite
Benchmark Name                          = newwithrdisc
Benchmark Runtime                       = 60.0
Benchmark Max Memory                    = 4000.0
Benchmark Runs                          = 10

#DB Path                                 = /home/nikolai/lststools/dune/misc/NO41620.sqlite
Min Planning Time                       = 60

# Froan
Start and Goal                          = 63.8687003,8.6656132, 63.8447657,8.4623738
Planning Bounds                         = 63.8153, 8.4561, 63.8924, 8.7003
Max Planning Time                       = 60

# Entering Nidelven
#Start and Goal                          = 63.44540, 10.38627,63.435066, 10.408719
#Max Planning Time                       = 100

# Long
#Start and Goal                          = 63.37453, 9.97640, 63.3481, 9.2028
#Planning Bounds                         = 63.261, 9.082, 63.795, 10.148
#Max Planning Time                       = 600

#Byneset
#Planning Bounds                         = 63.2555, 10.0024, 63.4952, 10.4897
#Start and Goal                          = 63.44540, 10.38627,63.34237, 10.22492
#Max Planning Time                       = 600