[Require ntnu-otter-01.ini]


[Control.Search.Greedy]
Enabled                                 = Always
Entity Label                            = GreedySearch
Debug Level                             = Spew
DB Path                                 = /home/nikolai/lststools/dune/misc/re4utmfinal.sqlite
Result DB Path                          = /home/nikolai/lststools/dune/misc/results.sqlite
Grid Type                               = 2
Grid Size                               = 75

[Monitors.CoveredArea]
Enabled                                 = Never
Entity Label                            = CoveredArea
Debug Level                             = Spew
Grid DB Path                            = /home/nikolai/lststools/dune/misc/coverage.sqlite
Grid Type                               = 1
Grid Size                               = 30
#Planning Bounds                         = 553574.0,7022280.1,555088.8,7023506.6
#Planning Bounds                         = 554570.5,7024614.1,556319.4,7026148.4
#Planning Bounds                         = 375241.1,6861101.2, 382285.4,6864796.3
Planning Bounds                         = 401084,6943662,409576,6954925

[Simulators.GPS]
#Initial Position                        = 61.892738, 6.702952
Initial Position                        = 62.63894,7.13026