#[Require ntnu-otter-01.ini]


[Control.Search.Greedy]
Enabled                                 = Always
Entity Label                            = GreedySearch
DB Path                                 = /home/nikolai/lststools/dune/misc/re4utmfinal.sqlite
Result DB Path                          = /home/nikolai/lststools/dune/misc/results.sqlite

#Planning Bounds                         = 540898,7019548,544316,7024636
#Start                                   = 544357,7024102
#Start                                   = 544399, 7022013
Grid Type                               = 1
Grid Size                               = 100

Planning Bounds                         = 566791, 7033807, 571507, 7036413
Start                                   = 567357, 7035439