[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone2
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
Delay Between Tag Messages              = 500

[Simulators.ThelmaHydrophone/T2]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Hydrophone
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/20220318tagDetections.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/01-30mrad90mdist.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/02-30mrad50mdistcoarse.csv
Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/03-30mrad50mdist.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/04-20mrad50mdist.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/05-10mrad50mdist-trash.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/06-15mrad50mdist-trash.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/07-15mrad50mdist.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/08-teleoperationComplete.csv
#Messagefile Path                        = /home/nikolai/Documents/NTNU/PhD/seaTrial/20220318/singleReceiverTest/09-endGarbage.csv
Delay Between Tag Messages              = 500

[Monitors.SpeedOfSoundInWater]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = SoundSpeedCalculator
Execution Frequency                     = 0.1
Initial Speed Of Sound                  = 1485
Use Temperature For Speed Of Sound      = true
Initial Temperature                     = 10.0
Initial Salinity                        = 25
Initial Depth                           = 1.0
Temperature - Entity                    = Hydrophone

[SourceEstimators.FishTag]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = FishTagEstimator
Use Speed Of Sound Measurement          = true
Speed Of Sound - Entity                 = SoundSpeedCalculator
Filter Timestep                         = 1
x0                                      = 1.0,1.0,-3.0
ToA Cov                                 = 5.8059
Depth Cov                               = 0.0001
Multi Receiver Estimators               = None
Single Receiver Estimators              = UKF#, UKF
SS - Extra Parameters - Name            = receiver_depth,max_jitter,max_updates_per_new_measurement,max_correction_attempts,interval_mode,tag_period,unscented_alpha,unscented_beta,unscented_kappa
SS - Extra Parameters - Value           = -3.0,0.3,1,1,2,10,1,2,1
Log Folder and Prefix                   = /home/nikolai/estimator/predict-
P0                                      = 66458, -26820, 1,
                                          -26820, 12116, 1,
                                          1, 1, 1
Depth Coefficient                       = 0.0

[SourceEstimators.SingleReceiverUKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorUKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
Max Correction Attempts                 = 0
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                       = 1.0, 0.0, 0.0,
                                          0.0, 1.0, 0.0,
                                          0.0, 0.0, 1.0
Rm                                       = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1
P0                                        = 1.0, 0.0, 0.0,
                                            0.0, 1.0, 0.0,
                                            0.0, 0.0, 0.1
Reference Coordinate					= 63.334, 10.084333
Alpha                                   = 0.01
Beta                                    = 25
Tag ID                                  = 200
Receiver Serial Number                  = 1000052
Tag Transmitt Period                    = 10
#Max Updates Per New Measurement         = 1
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                      = 1, 0.0, 0.0,
                                          0.0, 1, 0.0,
                                          0.0, 0.0, 1
Rm                                      = 5.8059, 0.0, 0.0,
                                          0.0, 5.8059 , 0.0,
                                          0.0, 0.0, 2.1638e6                                      
P0                                = 50000, -20000, 1,
                                          -20000, 50000, 1,
                                          1, 1, 10
Reference Coordinate					= 63.3342202,10.0740688

[SourceEstimators.SingleReceiverSRUKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorSRUKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
Max Correction Attempts                 = 1
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                       = 1.0, 0.0, 0.0,
                                          0.0, 1.0, 0.0,
                                          0.0, 0.0, 1.0
Rm                                       = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1
P0                                        = 1.0, 0.0, 0.0,
                                            0.0, 1.0, 0.0,
                                            0.0, 0.0, 1.0
Reference Coordinate					= 63.334, 10.084333
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0

[SourceEstimators.SingleReceiver]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = Estimatoren
Tag Transmitt Period                    = 10
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Receiver Serial Number                  = 1000052
Receiver Depth                          = 3.0
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 1
EKF - Qm                                = 0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.00001
EKF - Rm                                = 5.8059, 0,
                                          0, 2.1638e6
EKF - P0                                = 66458, -26820, 0,
                                          -26820, 12116, 0,
                                          0, 0, 0

[SourceEstimators.SingleReceiverDepth/1]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorwDepth
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Tag Transmitt Period                    = 7
Receiver Serial Number                  = 45
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 0.5
Receiver Depth                          = 3.0
EKF - Qm                                = 1, 0.0, 0.0,
                                          0.0, 1, 0.0,
                                          0.0, 0.0, 1
EKF - Rm                                = 10.0
#EKF - Rm                                = 5.8059, 0,
#                                         0, 2.1638e6
#EKF - Qm                                = 1.0, 0.0, 0.0,
#                                          0.0, 1.0, 0.0,
#                                          0.0, 0.0, 1.0
#EKF - Rm                                = 10.0, 0.0, 0.0,
#                                          0.0, 500000, 0.0,
#                                          0.0, 0.0, 0.2
EKF - P0                                = 50000, -20000, 1,
                                          -20000, 50000, 1,
                                          1, 1, 10
Reference Coordinate					= 63.3342202,10.0740688

[SourceEstimators.SingleReceiver/2]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorSverre
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 0.5
Receiver Depth                          = 3.0
EKF - Qm                                = 1, 0.0, 0.0,
                                          0.0, 1, 0.0,
                                          0.0, 0.0, 1
#EKF - Rm                                = 10.0
#EKF - Rm                                = 5.8059, 0,
#                                         0, 2.1638e6
#EKF - Qm                                = 1.0, 0.0, 0.0,
#                                          0.0, 1.0, 0.0,
#                                          0.0, 0.0, 1.0
#EKF - Rm                                = 10.0, 0.0, 0.0,
#                                          0.0, 500000, 0.0,
#                                          0.0, 0.0, 0.2
EKF - Rm                                = 5.8059, 0,
                                          0, 2.1638e6
EKF - P0                                = 66458, -26820, 0,
                                          -26820, 12116, 0,
                                          0, 0, 0
Reference Coordinate					= 63.3342202,10.0740688
