#[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Hydrophone
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_convex.csv
Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/20220303.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_orbital.csv
#Messagefile Path                        = /home/nikolai/SverreData/sverre_concave.csv
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/forsim2.csv
Delay Between Tag Messages              = 1000

[SourceEstimators.FishTag]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = FishTagEstimator40
Filter Timestep                         = 0.5
x0                                      = 0,0,0
ToA Cov                                 = 1.0
Depth Cov                               = 0.1

[SourceEstimators.SingleReceiverUKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorUKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
Max Correction Attempts                 = 0
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                       = 1.0, 0.0, 0.0,
                                          0.0, 1.0, 0.0,
                                          0.0, 0.0, 1.0
Rm                                       = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1
P0                                        = 1.0, 0.0, 0.0,
                                            0.0, 1.0, 0.0,
                                            0.0, 0.0, 0.1
Reference Coordinate					= 63.334, 10.084333
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0

[SourceEstimators.SingleReceiverEKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorEKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Receiver Serial Number                  = 1000052
Tag Transmitt Period                    = 10
Max Correction Attempts                 = 0
Max Updates Per New Measurement         = 1
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                      = 0, 0.0, 0.0,
                                          0.0, 0, 0.0,
                                          0.0, 0.0, 0.001
Rm                                      = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1                                         
P0                                      = 1, 0, 0,
                                          0, 1, 0,
                                          0, 0, 1
Reference Coordinate					= 63.334, 10.084333

[SourceEstimators.SingleReceiverSRUKF]
Enabled                                 = Never
Debug Level                             = Spew
Entity Label                            = EstimatorSRUKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 200
Tag Transmitt Period                    = 10
Receiver Serial Number                  = 1000052
Max Correction Attempts                 = 1
Filter Timestep                         = 0.500
Receiver Depth                          = -1.0
Qm                                       = 1.0, 0.0, 0.0,
                                          0.0, 1.0, 0.0,
                                          0.0, 0.0, 1.0
Rm                                       = 1.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.1
P0                                        = 1.0, 0.0, 0.0,
                                            0.0, 1.0, 0.0,
                                            0.0, 0.0, 1.0
Reference Coordinate					= 63.334, 10.084333
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0
