[Require ntnu-otter-01.ini]

[Simulators.ThelmaHydrophone]
Enabled                                 = Never
Debug Level                             = None
Entity Label                            = Hydrophone
Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/sampleInput.txt
Delay Between Tag Messages              = 7000

[SourceEstimators.SingleSource/P631]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Estimator631
Ranging - SNR Fit                       = -0.0845, 50.8098
#Ranging - SNR Fit                       = -0.0971, 41.6358
Tag ID                                  = 40
PF - Particles Per Direction            = 50
Receiver Serial Number                  = 631
Max Correction Attempts                 = 1
Filter Timestep                         = 7
EKF - Qm                                = 2.0, 0.0, 0.0,
                                          0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.00001
EKF - Rm                                = 1.5*3.8706,
                                          0, 0, 2.1638e6
EKF - P0                                = 66458, -26820, 0,
                                          -26820, 12116,
                                          0, 0, 0, 0
UTM Zone                                = 34

[SourceEstimators.SingleSource/P632]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Estimator632
Ranging - SNR Fit                       = -0.0845, 50.8098
#Ranging - SNR Fit                       = -0.0971, 41.6358
Tag ID                                  = 40
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 7
EKF - Qm                                = 2.0, 0.0, 0.0,
                                          0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.00001
EKF - Rm                                = 1.5*3.8706,
                                          0, 0, 2.1638e6
EKF - P0                                = 66458, -26820, 0,
                                          -26820, 12116,
                                          0, 0, 0, 0
UTM Zone                                = 34
Receiver Serial Number                  = 632

[SourceEstimators.SingleSource/P634]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Estimator634
Ranging - SNR Fit                       = -0.0845, 50.8098
#Ranging - SNR Fit                       = -0.0971, 41.6358
Tag ID                                  = 40
PF - Particles Per Direction            = 50
Max Correction Attempts                 = 1
Filter Timestep                         = 7
EKF - Qm                                = 2.0, 0.0, 0.0,
                                          0.0, 0.0, 0.0,
                                          0.0, 0.0, 0.00001
EKF - Rm                                = 1.5*3.8706,
                                          0, 0, 2.1638e6
EKF - P0                                = 66458, -26820, 0,
                                          -26820, 12116,
                                          0, 0, 0, 0
UTM Zone                                = 34
Receiver Serial Number                  = 634

[Simulators.FishTag]
Enabled                                 = Never
Execution Frequency                     = 0.142857143
Entity Label                            = FishTag
Initial Position                        = 63.334, 10.083333
Initial Depth                           = 2
Time Disturbance Mean value             = 1
Time Disturbance Standard deviation     = 0.01
Time Offset                             = 0


[Navigation.FishEstimation.TBRTest]
Entity Label                            = RangeSensor
Enabled                                 = Always
Execution Frequency                     = 100
Debug Level                             = Spew

[SourceEstimators.FishTagXKF]
Entity Label                            = XKF_FishPosition
Enabled                                 = Always
Debug Level 							= Debug
Execution Frequency                     = 1
FishPos Cov                             = 1
ToA Cov                                 = 2.0
Depth Cov                               = 0.2

Speed of sound in water [m/s] 			= 1485
Max time shift [ms]						= 500

#GPS position (lat, lon) of the reference coordinate frame in degrees
Reference Coordinate					= 59.302713, 18.217311
Initial Position						= 1000, 1000, 70