[Simulators.ThelmaHydrophone]
Enabled                                 = Always
Debug Level                             = None
Entity Label                            = Hydrophone
#Messagefile Path                        = /home/nikolai/lststools/dune/user/src/Simulators/ThelmaHydrophone/sampleInput.txt
#Messagefile Path                        = /home/nikolai/lststools/dune/src/Simulators/ThelmaHydrophone/circleConverge.csv
Messagefile Path                        = /home/nikolai/sverre_convex.csv
Delay Between Tag Messages              = 100

[SourceEstimators.SingleReceiverDepth]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = Estimator
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Max Correction Attempts                 = 1
Filter Timestep                         = 0.050
Receiver Depth                          = -3.0
Reference Coordinate					= 63.32983, 10.07732

[SourceEstimators.SingleReceiverUKF/1]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = EstimatorUKF1
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Max Correction Attempts                 = 1
Filter Timestep                         = 0.050
Receiver Depth                          = -3.0
Qm                                       = 0, 0.0, 0.0,
                                          0.0, 0, 0.0,
                                          0.0, 0.0, 0.001
Rm                                       = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                        = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.32983, 10.07732
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0


[SourceEstimators.SingleReceiverUKF/2]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = EstimatorUKF2
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Max Correction Attempts                 = 1
Filter Timestep                         = 0.050
Receiver Depth                          = -3.0
Qm                                       = 0, 0.0, 0.0,
                                          0.0, 0, 0.0,
                                          0.0, 0.0, 0.001
Rm                                       = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                        = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.32983, 10.07732
Alpha                                   = 0.001
Beta                                    = 2
Kappa                                   = 0


[SourceEstimators.SingleReceiverUKF/3]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = EstimatorUKF3
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Max Correction Attempts                 = 1
Filter Timestep                         = 0.050
Receiver Depth                          = -3.0
Qm                                      = 0.1, 0.0, 0.0,
                                          0.0, 0.1, 0.0,
                                          0.0, 0.0, 0.001
Rm                                      = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                      = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.32983, 10.07732
Alpha                                   = 0.01
Beta                                    = 2
Kappa                                   = 0

[SourceEstimators.SingleReceiverEKF]
Enabled                                 = Always
Debug Level                             = Spew
Entity Label                            = EstimatorEKF
Ranging - SNR Fit                       = -0.0845, 50.8098
Tag ID                                  = 40
Receiver Serial Number                  = 45
Max Correction Attempts                 = 1
Filter Timestep                         = 0.050
Receiver Depth                          = -3.0
Qm                                      = 0, 0.0, 0.0,
                                          0.0, 0, 0.0,
                                          0.0, 0.0, 0.001
Rm                                      = 3.0, 0.0, 0.0,
                                          0.0, 5000000, 0.0,
                                          0.0, 0.0, 0.2                                          
P0                                      = 3000, -2000, 0,
                                          -2000, 3000, 0,
                                          0, 0, 10
Reference Coordinate					= 63.32983, 10.07732